### ISSUE TITLE
docker exec web python manage.py createsuperuser

### ISSUE THREAD

**Issue by parhamgh2020** [htondro/realtyna-challenge#3]
django.db.utils.OperationalError: connection to server at "db" (172.20.0.2), port 5432 failed: FATAL:  database "realtyna" does not exist

**Comment by htondro** [comment]
You get this error because docker didn't create the database for you.
I was considered "creating the database" as a step to do in the deployment guide too, But I found a better way.
By setting the correct env vars, docker will create the database while building.
Actually I had a typo in `.env` file, I set `POSTGRESS_DATABASE=realtyna` while I should set `POSTGRESS_DB=realtyna`.
Thanks to you for pointing out the issue.
